######################################################################
# 🧱 Docker Compose — Gluetun VPN + qBittorrent
#
# ▶️ This stack routes all BitTorrent traffic through Gluetun VPN (ProtonVPN,
#    WireGuard, or OpenVPN).
#
# ⚙️ Usage:
#   - Fill your .env file with VPN credentials and media paths.
#   - Run: docker-compose up -d
#   - Access UIs:
#       • qBittorrent → http://localhost:65534
######################################################################

services:
  ######################################################################
  # 🛡️ GLUETUN — VPN container
  # Provides a secure VPN tunnel (ProtonVPN, Mullvad, etc.).
  ######################################################################
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${WEBUI_PORT}:${WEBUI_PORT}/tcp 
      - 8000:8000                     
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      UPDATER_PERIOD: ${UPDATER_PERIOD}
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      VPN_TYPE: ${VPN_TYPE}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_CIPHERS: ${OPENVPN_CIPHERS}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      VPN_PORT_FORWARDING: ${VPN_PORT_FORWARDING}
      PORT_FORWARD_ONLY: ${PORT_FORWARD_ONLY}
    volumes:
      - ${CONFIG_PATH}/gluetun:/gluetun
      - ./auth:/gluetun/auth
    restart: unless-stopped

  ######################################################################
  # 🧲 QBITTORRENT — BitTorrent client (optionally with VueTorrent UI)
  ######################################################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      WEBUI_PORT: ${WEBUI_PORT} 
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest # Optional: modern VueTorrent UI
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${MEDIA_DIR}/downloads:/downloads
    restart: unless-stopped

  ######################################################################
  # 🔀 PORT FORWARDING HELPER — Build local image & update and keep qBittorrent port open
  ######################################################################
  qbittorrent-port-forward-gluetun-server:
    build:
      context: ./qbittorrent-port-forward-gluetun-server   
      dockerfile: Dockerfile                               
    container_name: qbittorrent-port-forward-gluetun-server
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - .env
    environment:
      QBT_USERNAME: ${QBT_USERNAME}
      QBT_PASSWORD: ${QBT_PASSWORD}
      QBT_ADDR: http://127.0.0.1:${WEBUI_PORT}
      GTN_ADDR: http://127.0.0.1:8000
      GTN_APIKEY: ${GLUETUN_AUTH_API_KEY}
    restart: unless-stopped