
######################################################################
# Docker Compose for Gluetun VPN + Transmission BitTorrent Client
#
# This stack securely routes Transmission traffic through a VPN (Gluetun)
# supporting ProtonVPN and other providers, with WireGuard or OpenVPN.
# Transmission runs inside the VPN container's network for privacy and port forwarding.
#
# Usage:
#  - Configure .env file with your VPN credentials and paths
#  - Start with: docker-compose up -d
#  - Access Transmission Web UI at http://localhost:9091
#
# For more info, see:
services:
  ######################################################################
  # 🛡️ GLUETUN — VPN CONTAINER (ProtonVPN, WireGuard or OpenVPN)
  # Routes all traffic of connected services (Transmission, etc.)
  # Handles all VPN connectivity and port forwarding for Transmission
  ######################################################################
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    network_mode: bridge # Standard Docker bridge network
    cap_add:
      - NET_ADMIN # Required for VPN networking (allows routing changes)
    devices:
      - /dev/net/tun:/dev/net/tun # TUN device required for VPN tunnel
    ports:
      - 9091:9091 # Exposes Transmission Web UI (via VPN)
      - 8000:8000 # Exposes Gluetun Control server
      - 9696:9696 # Exposes Prowlarr Web UI
      - 7878:7878 # Exposes Radarr Web UI
      - 8989:8989 # Exposes Sonarr Web UI
    env_file:
      - .env # Loads environment variables from .env file
    environment:
      TZ: ${TZ}
      UPDATER_PERIOD: ${UPDATER_PERIOD}
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      VPN_TYPE: ${VPN_TYPE}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_CIPHERS: ${OPENVPN_CIPHERS}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      VPN_PORT_FORWARDING: ${VPN_PORT_FORWARDING}
      PORT_FORWARD_ONLY: ${PORT_FORWARD_ONLY}
    volumes:
      - ${CONFIG_PATH}/gluetun:/gluetun
      - ./auth:/gluetun/auth
    restart: unless-stopped

  ######################################################################
  # 🧲 TRANSMISSION — BitTorrent Client (Flood Web UI)
  # Runs inside Gluetun’s VPN network stack (network_mode: service:gluetun)
  # Runs inside Gluetun’s VPN network for privacy and port forwarding
  ######################################################################
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DOCKER_MODS: linuxserver/mods:transmission-floodui|linuxserver/mods:transmission-env-var-settings|michaukrieg/docker-mods:transmission-gluetun-port-update
      GLUETUN_AUTH_TYPE: ${GLUETUN_AUTH_TYPE}
      GLUETUN_AUTH_API_KEY: ${GLUETUN_AUTH_API_KEY}
      TRANSMISSION_USER: ${TRANSMISSION_USER}
      TRANSMISSION_PASSWORD: ${TRANSMISSION_PASSWORD}
    volumes:
      - ${CONFIG_PATH}/transmission:/config
      - ${MEDIA_DIR}/downloads:/downloads
      - ${MEDIA_DIR}/watch:/watch
    restart: unless-stopped

  ######################################################################
  # 🦅 PROWLARR — Indexer Manager for Torrent Trackers
  # Manages torrent indexers and integrates with Transmission
  # Runs inside Gluetun’s VPN network for privacy and port forwarding
  ######################################################################
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/almottier/prowlarr-ygg
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    restart: unless-stopped

  
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_DIR}/movies:/movies 
      - ${MEDIA_DIR}/downloads:/downloads
    restart: unless-stopped


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_DIR}/tv:/tv
      - ${MEDIA_DIR}/downloads:/downloads
    restart: unless-stopped